/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tiendadezapatos.view;

import com.mycompany.tiendadezapatos.dao.ProveedorDAO;
import com.mycompany.tiendadezapatos.model.Proveedor;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JJAB
 */
public class AdministrarProveedoresView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministrarProveedores
     */
    private DefaultTableModel dtm;
    private ProveedorDAO proveedorDAO = new ProveedorDAO();

    public AdministrarProveedoresView() {
        initComponents();
        crearTabla();
        CargarTabla();
    }

    private void crearTabla() {
        dtm = new DefaultTableModel();
        dtm.addColumn("id");
        dtm.addColumn("ruc");
        dtm.addColumn("codigo");
        dtm.addColumn("nombre");
        dtm.addColumn("telefono");
        dtm.addColumn("correo");
        dtm.addColumn("registro");

        tblProveedor.setModel(dtm);

        tblProveedor.getColumnModel().getColumn(0).setPreferredWidth(6);
        tblProveedor.getColumnModel().getColumn(0).setResizable(false);

        tblProveedor.getColumnModel().getColumn(1).setPreferredWidth(54);
        tblProveedor.getColumnModel().getColumn(1).setResizable(false);

        tblProveedor.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblProveedor.getColumnModel().getColumn(2).setResizable(false);

        tblProveedor.getColumnModel().getColumn(3).setPreferredWidth(55);
        tblProveedor.getColumnModel().getColumn(3).setResizable(false);

        tblProveedor.getColumnModel().getColumn(4).setPreferredWidth(55);
        tblProveedor.getColumnModel().getColumn(4).setResizable(false);

        tblProveedor.getColumnModel().getColumn(5).setPreferredWidth(90);
        tblProveedor.getColumnModel().getColumn(5).setResizable(false);

        tblProveedor.getColumnModel().getColumn(6).setPreferredWidth(50);
        tblProveedor.getColumnModel().getColumn(6).setResizable(false);

    }

    private void CargarTabla() {

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        List<Proveedor> lista = proveedorDAO.obtenerProveedor();

        if (lista.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No existen proveedores");

        } else {

            for (Proveedor p : lista) {
                dtm.addRow(new Object[]{
                    p.getIdproveedor(), p.getRuc(), p.getCodigoproveedor(), p.getNombre(), p.getTelefono(),
                    p.getCorreo(), formato.format(p.getFechaderegistro())
                });
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAdministrar = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        txtRuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelAdministrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N

        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed1(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Telefono");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Correo");

        btnSeleccionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        txtRuc.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Ruc");

        javax.swing.GroupLayout panelAdministrarLayout = new javax.swing.GroupLayout(panelAdministrar);
        panelAdministrar.setLayout(panelAdministrarLayout);
        panelAdministrarLayout.setHorizontalGroup(
            panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo)
                    .addComponent(txtTelefono)
                    .addComponent(txtNombre)
                    .addComponent(txtRuc)
                    .addGroup(panelAdministrarLayout.createSequentialGroup()
                        .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(panelAdministrarLayout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAdministrarLayout.setVerticalGroup(
            panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N

        tblProveedor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProveedor);

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAdministrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {
            String buscar = txtBuscar.getText();

            List<Proveedor> lista = proveedorDAO.hacerBusquedaProveedor(buscar);

            if (lista.isEmpty()) {

                JOptionPane.showMessageDialog(this, "No existen proveedores", "Buscar", JOptionPane.INFORMATION_MESSAGE);

            } else {

                crearTabla();

                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                for (Proveedor p : lista) {
                    dtm.addRow(new Object[]{
                        p.getIdproveedor(), p.getRuc(), p.getCodigoproveedor(), p.getNombre(), p.getTelefono(),
                        p.getCorreo(), formato.format(p.getFechaderegistro())
                    });
                }

            }

        } catch (Exception e) {
            System.out.println("no se puede cargar los datos vista " + e);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed1

        if (txtRuc.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Seleccione una fila", "Actualizar", JOptionPane.INFORMATION_MESSAGE);

        } else {

            int id = (int) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 0);

            boolean actualizar = proveedorDAO.actualizarProveedor(id, txtNombre.getText(), txtTelefono.getText(), txtCorreo.getText());

            if (actualizar) {
                crearTabla();
                CargarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se puede actualizar el regisrtro", "Verifique los campos", JOptionPane.INFORMATION_MESSAGE);

            }

        }

    }//GEN-LAST:event_btnActualizarActionPerformed1

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        try {

            int id = (int) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 0);

            int opcion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el registro?", "Eliminar", JOptionPane.YES_NO_OPTION);

            if (opcion == 0) {

                boolean eliminar = proveedorDAO.eliminarProveedor(id);

                if (eliminar) {
                    crearTabla();
                    CargarTabla();
                    limpiarCampos();
                    JOptionPane.showMessageDialog(this, "El registro se elimino correctamente", "Eliminar", JOptionPane.OK_OPTION);

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila", "Seleccionar", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

        try {

            txtRuc.setText((String) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 1));
            txtNombre.setText((String) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 3));
            txtTelefono.setText((String) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 4));
            txtCorreo.setText((String) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 5));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila", "Seleccionar", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void limpiarCampos() {
        for (Component c : panelAdministrar.getComponents()) {
            if (c instanceof JTextField jTextField) {
                jTextField.setText("");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAdministrar;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
