/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tiendadezapatos.view;

import com.mycompany.tiendadezapatos.model.CompraMercancia;
import com.mycompany.tiendadezapatos.model.Mercancia;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author JJAB
 */
public class CompraRealizadaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CompraRealizada
     */
    private List<Mercancia> mercancias;
    private String total = null;

    public CompraRealizadaView() {
        initComponents();
        mercancias = new ArrayList<>();

    }

    public void obtenerCompraMercancia(CompraMercancia compraMercancia) {

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        lblfechaDeCompra.setText("" + formato.format(compraMercancia.getFechacompra()));
        lblCorreo.setText(compraMercancia.getProveedorIdproveedor().getNombre());
        total = "" + compraMercancia.getTotal();
    }

    public void crearListaMercancia(Mercancia mercancia) {
        mercancias.add(mercancia);
    }

    public void obtenerMercancia() {
        for (int i = 0; i < mercancias.size(); i++) {
            panelMercancia.append("Codigo: " + mercancias.get(i).getCodigo() + " Nombre: " + mercancias.get(i).getNombre()
                    + " PrecioCompra " + mercancias.get(i).getPrecioCompraUnidad() + " PrecioVenta " + mercancias.get(i).getPrecioVentaUnidad()
                    + " Cantidad " + mercancias.get(i).getStock() + '\n'
            );
        }
        panelMercancia.append("Total: " + total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblfechaDeCompra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMercancia = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setClosable(true);

        jLabel1.setText("Proveedor");

        lblfechaDeCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Fecha");

        lblCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelMercancia.setColumns(20);
        panelMercancia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelMercancia.setRows(5);
        panelMercancia.setEnabled(false);
        jScrollPane1.setViewportView(panelMercancia);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Imprimir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblfechaDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfechaDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblfechaDeCompra;
    private javax.swing.JTextArea panelMercancia;
    // End of variables declaration//GEN-END:variables
}
