/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.tiendadezapatos.view;

/**
 *
 * @author JJAB
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mniVentas = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        mniIngresarProveedor = new javax.swing.JMenuItem();
        mniMercaderia = new javax.swing.JMenuItem();
        mniCliente = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniAdministrarProveedor = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniHacerPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jMenu3.setText("Ventas");

        mniVentas.setText("Ventas");
        mniVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentasActionPerformed(evt);
            }
        });
        jMenu3.add(mniVentas);

        menuBar.add(jMenu3);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Ingresar");

        mniIngresarProveedor.setMnemonic('o');
        mniIngresarProveedor.setText("Proveedor");
        mniIngresarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniIngresarProveedorActionPerformed(evt);
            }
        });
        fileMenu.add(mniIngresarProveedor);

        mniMercaderia.setText("Mercaderia");
        mniMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMercaderiaActionPerformed(evt);
            }
        });
        fileMenu.add(mniMercaderia);

        mniCliente.setText("Cliente");
        mniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClienteActionPerformed(evt);
            }
        });
        fileMenu.add(mniCliente);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu2.setText("Administrar");

        mniAdministrarProveedor.setText("Proveedor");
        mniAdministrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdministrarProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(mniAdministrarProveedor);

        menuBar.add(jMenu2);

        jMenu1.setText("Pedidos");

        mniHacerPedido.setText("Hacer Pedidos");
        mniHacerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHacerPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(mniHacerPedido);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mniIngresarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniIngresarProveedorActionPerformed

        panelPrincipal.removeAll();
        panelPrincipal.repaint();

        AgregarProveedorView agregarProveedorView = new AgregarProveedorView();
        agregarProveedorView.setVisible(true);
        panelPrincipal.add(agregarProveedorView);

    }//GEN-LAST:event_mniIngresarProveedorActionPerformed

    private void mniAdministrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdministrarProveedorActionPerformed

        panelPrincipal.removeAll();
        panelPrincipal.repaint();

        AdministrarProveedoresView administrarProveedoresView = new AdministrarProveedoresView();
        administrarProveedoresView.setVisible(true);
        panelPrincipal.add(administrarProveedoresView);

    }//GEN-LAST:event_mniAdministrarProveedorActionPerformed

    private void mniMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMercaderiaActionPerformed

        panelPrincipal.removeAll();
        panelPrincipal.repaint();

        SeleccionarProveedorView seleccionarProveedorView = new SeleccionarProveedorView();
        seleccionarProveedorView.setVisible(true);

        seleccionarProveedorView.setSeleccionarventana("agregarmercancia");

        panelPrincipal.add(seleccionarProveedorView);
    }//GEN-LAST:event_mniMercaderiaActionPerformed

    private void mniHacerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHacerPedidoActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.repaint();

        SeleccionarProveedorView seleccionarProveedorView = new SeleccionarProveedorView();
        seleccionarProveedorView.setVisible(true);

        seleccionarProveedorView.setSeleccionarventana("hacerpedido");

        panelPrincipal.add(seleccionarProveedorView);
    }//GEN-LAST:event_mniHacerPedidoActionPerformed

    private void mniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClienteActionPerformed

        panelPrincipal.removeAll();
        panelPrincipal.repaint();

        AgregarClienteView agregarClienteView = new AgregarClienteView();
        agregarClienteView.setVisible(true);

        panelPrincipal.add(agregarClienteView);


    }//GEN-LAST:event_mniClienteActionPerformed

    private void mniVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentasActionPerformed

        panelPrincipal.removeAll();
        panelPrincipal.repaint();

        RealizarVentaView realizarVenta = new RealizarVentaView();
        realizarVenta.setVisible(true);
        
        panelPrincipal.add(realizarVenta);
    }//GEN-LAST:event_mniVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniAdministrarProveedor;
    private javax.swing.JMenuItem mniCliente;
    private javax.swing.JMenuItem mniHacerPedido;
    private javax.swing.JMenuItem mniIngresarProveedor;
    private javax.swing.JMenuItem mniMercaderia;
    private javax.swing.JMenuItem mniVentas;
    public static javax.swing.JDesktopPane panelPrincipal;
    // End of variables declaration//GEN-END:variables

}
