/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tiendadezapatos.view;

import com.mycompany.tiendadezapatos.dao.ProveedorDAO;
import com.mycompany.tiendadezapatos.model.Proveedor;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JJAB
 */
public class SeleccionarProveedorView extends javax.swing.JInternalFrame {

    private DefaultTableModel dtmProveedor;
    private ProveedorDAO proveedorDAO = new ProveedorDAO();
    private String seleccionarventana;

    public void setSeleccionarventana(String seleccionarventana) {
        this.seleccionarventana = seleccionarventana;
    }

    /**
     * Creates new form SeleccionarProveedor
     */
    public SeleccionarProveedorView() {
        initComponents();
        crearTablaProveedor();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        btnAgregarProveedor = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Proveedor"));

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProveedor);

        btnSeleccionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnAgregarProveedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregarProveedor.setText("Agregar Proveedor");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarProveedor)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSeleccionar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearTablaProveedor() {
        dtmProveedor = new DefaultTableModel();
        dtmProveedor.addColumn("id");
        dtmProveedor.addColumn("ruc");
        dtmProveedor.addColumn("codigo");
        dtmProveedor.addColumn("nombre");
        dtmProveedor.addColumn("telefono");
        dtmProveedor.addColumn("correo");
        dtmProveedor.addColumn("registro");

        tblProveedor.setModel(dtmProveedor);

        tblProveedor.getColumnModel().getColumn(0).setPreferredWidth(6);
        tblProveedor.getColumnModel().getColumn(0).setResizable(false);

        tblProveedor.getColumnModel().getColumn(1).setPreferredWidth(54);
        tblProveedor.getColumnModel().getColumn(1).setResizable(false);

        tblProveedor.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblProveedor.getColumnModel().getColumn(2).setResizable(false);

        tblProveedor.getColumnModel().getColumn(3).setPreferredWidth(55);
        tblProveedor.getColumnModel().getColumn(3).setResizable(false);

        tblProveedor.getColumnModel().getColumn(4).setPreferredWidth(55);
        tblProveedor.getColumnModel().getColumn(4).setResizable(false);

        tblProveedor.getColumnModel().getColumn(5).setPreferredWidth(90);
        tblProveedor.getColumnModel().getColumn(5).setResizable(false);

        tblProveedor.getColumnModel().getColumn(6).setPreferredWidth(50);
        tblProveedor.getColumnModel().getColumn(6).setResizable(false);
    }

    private void CargarTabla() {

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        List<Proveedor> lista = proveedorDAO.obtenerProveedor();

        if (lista.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No existen proveedores");

        } else {

            for (Proveedor p : lista) {
                dtmProveedor.addRow(new Object[]{
                    p.getIdproveedor(), p.getRuc(), p.getCodigoproveedor(), p.getNombre(), p.getTelefono(),
                    p.getCorreo(), formato.format(p.getFechaderegistro())
                });
            }

        }

    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

        if (seleccionarventana.equals("agregarmercancia")) {

            int id = (int) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 0);
            try {

                this.setVisible(false);

                AgregarMercaderiaView agregarMercaderiaView = new AgregarMercaderiaView();

                //Enviar id del proveedor
                agregarMercaderiaView.ObtenerIdProveedor(id);

                agregarMercaderiaView.setVisible(true);
                PrincipalView.panelPrincipal.add(agregarMercaderiaView);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se puede obtener el proveedor " + e);

            }

        } else if (seleccionarventana.equals("hacerpedido")) {

            try {

                int id = (int) tblProveedor.getModel().getValueAt(tblProveedor.getSelectedRow(), 0);
                
               // this.setVisible(false);

               this.setClosed(true);
               
               RealizarPedidoView seleccionarMercaderiaView = new RealizarPedidoView();

                //Enviar id del proveedor
                seleccionarMercaderiaView.obtenerIdProveedor(id);

                seleccionarMercaderiaView.setVisible(true);
                PrincipalView.panelPrincipal.add(seleccionarMercaderiaView);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se puede obtener el proveedor " + e);

            }

        }


    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
