-- MySQL Script generated by MySQL Workbench
-- Thu Jan  2 15:36:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendadezapatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendadezapatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendadezapatos` DEFAULT CHARACTER SET utf8 ;
USE `tiendadezapatos` ;

-- -----------------------------------------------------
-- Table `tiendadezapatos`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(45) NOT NULL,
  `codigoproveedor` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fechaderegistro` DATE NOT NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`mercancia` (
  `idmercancia` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `precio_compra_unidad` DECIMAL(8,2) NOT NULL,
  `precio_venta_unidad` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`idmercancia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fechaderegistro` DATETIME NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `fechafactura` DATETIME NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_factura_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `tiendadezapatos`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`detalle_factura` (
  `iddetalle_factura` INT NOT NULL AUTO_INCREMENT,
  `mercancia_idmercancia` INT NOT NULL,
  `factura_idfactura` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`iddetalle_factura`),
  INDEX `fk_detalle_factura_mercancia1_idx` (`mercancia_idmercancia` ASC) VISIBLE,
  INDEX `fk_detalle_factura_factura1_idx` (`factura_idfactura` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_factura_mercancia1`
    FOREIGN KEY (`mercancia_idmercancia`)
    REFERENCES `tiendadezapatos`.`mercancia` (`idmercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`factura_idfactura`)
    REFERENCES `tiendadezapatos`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`compra_mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`compra_mercancia` (
  `idcompra_mercancia` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(8,2) NOT NULL,
  `fechacompra` DATETIME NOT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  PRIMARY KEY (`idcompra_mercancia`),
  INDEX `fk_compra_mercancia_proveedor1_idx` (`proveedor_idproveedor` ASC) VISIBLE,
  CONSTRAINT `fk_compra_mercancia_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `tiendadezapatos`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`detalle_compra` (
  `iddetalle_compra` INT NOT NULL AUTO_INCREMENT,
  `mercancia_idmercancia` INT NOT NULL,
  `compra_mercancia_idcompra_mercancia` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`iddetalle_compra`),
  INDEX `fk_compra_mercaderia_mercancia1_idx` (`mercancia_idmercancia` ASC) VISIBLE,
  INDEX `fk_compra_mercaderia_compra_mercancia1_idx` (`compra_mercancia_idcompra_mercancia` ASC) VISIBLE,
  CONSTRAINT `fk_compra_mercaderia_mercancia1`
    FOREIGN KEY (`mercancia_idmercancia`)
    REFERENCES `tiendadezapatos`.`mercancia` (`idmercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_mercaderia_compra_mercancia1`
    FOREIGN KEY (`compra_mercancia_idcompra_mercancia`)
    REFERENCES `tiendadezapatos`.`compra_mercancia` (`idcompra_mercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_proveedor1_idx` (`proveedor_idproveedor` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `tiendadezapatos`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`detallepedido` (
  `iddetallepedido` INT NOT NULL AUTO_INCREMENT,
  `pedido_idpedido` INT NOT NULL,
  `mercancia_idmercancia` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`iddetallepedido`),
  INDEX `fk_detallepedido_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_detallepedido_mercancia1_idx` (`mercancia_idmercancia` ASC) VISIBLE,
  CONSTRAINT `fk_detallepedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `tiendadezapatos`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallepedido_mercancia1`
    FOREIGN KEY (`mercancia_idmercancia`)
    REFERENCES `tiendadezapatos`.`mercancia` (`idmercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadezapatos`.`actualizarprecio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadezapatos`.`actualizarprecio` (
  `actualizarprecio` INT NOT NULL AUTO_INCREMENT,
  `antiguopreciocompra` DECIMAL(8,2) NOT NULL,
  `antiguoprecioventa` DECIMAL(8,2) NOT NULL,
  `nuevopreciocompra` DECIMAL(8,2) NOT NULL,
  `nuevoprecioventa` DECIMAL(8,2) NOT NULL,
  `mercancia_idmercancia` INT NOT NULL,
  `detallepedido_iddetallepedido` INT NOT NULL,
  PRIMARY KEY (`actualizarprecio`),
  INDEX `fk_actualizarprecio_detallepedido1_idx` (`detallepedido_iddetallepedido` ASC) VISIBLE,
  CONSTRAINT `fk_actualizarprecio_detallepedido1`
    FOREIGN KEY (`detallepedido_iddetallepedido`)
    REFERENCES `tiendadezapatos`.`detallepedido` (`iddetallepedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `tiendadezapatos`.`proveedor` (`ruc`, `codigoproveedor`, `nombre`, `telefono`, `correo`, `fechaderegistro`) VALUES
 ('2041478965001', '53980', 'Saunayta', '0983746356', 'sususu@gmsil.com', '2024-12-15'),
 ('0258745336001', '97427', 'Zarita', '0987457122', 'sssraa@mss.com', '2024-11-30'),
 ('0632541243001', '75170', 'BabelShop', '0957648321', 'balshop@gmail.com', '2024-07-30');
  
  INSERT INTO `tiendadezapatos`.`cliente` (`cedula`, `nombres`, `telefono`, `correo`, `fechaderegistro`) VALUES
  ('999999999', 'consumidorFinal', '999999999', '99999999999', '2024-12-14 14:22:41'),
  ('2408745120', 'Susana Mora', '0943567332', 'offcpl@ggkgk.com', '2024-12-14 14:25:15'),
  ('2274521412', 'Martha Frias', '0983435653', 'jnnf@fjfj.vok', '2024-12-15 19:57:27');
  
  INSERT INTO `tiendadezapatos`.`mercancia` (`codigo`, `nombre`, `stock`, `precio_compra_unidad`, `precio_venta_unidad`) VALUES 
  ('974276664', 'zapatos rayas 32', '25', '1.74', '80.99'),
  ('974271237', 'botas cuero negro 36', '23', '22.45', '49.33'),
  ('240886502', 'Oshtru classic 40', '20', '8.22', '26.99'),
  ('240889627', 'Oshtru classic 37', '107', '25.00', '53.79'),
  ('974272627', 'sandalia alia negra 40', '72', '15.25', '35.44'),
  ('974274285', 'zapatos lona 38', '24', '5.50', '8.55'),
  ('751703892', 'Tacones rojos 35', '30', '2.44', '50.44'),
  ('751702772', 'botines cuero negro 39', '32', '18.22', '32.68'),
  ('751701864', 'sandalia de plataforma 38', '32', '12.55', '35.44');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
